const data = {
  products: [
    {
      name: 'RTX 3070 Gigabyte',
      category: 'Placa de video',
      slug: 'placa-video',
      image: '/images/placa1.jpg',
      price: 'u$ 1500',
      minBuy: '10 unidades',
      description: 'Placa de video gigabyte 8GB OC gamming',
    },
    {
      name: 'RTX 3090 Gigabyte',
      category: 'Placa de video',
      slug: 'placa-video',
      image: '/images/placa 2.jpg',
      price: 'u$ 1990',
      minBuy: '20 unidades',
      description: 'Placa de video gigabyte 8GB OC gamming',
    },
    {
      name: 'Silla Gammer',
      category: 'Sillas',
      slug: 'silla-gammer',
      image: '/images/silla1.jpg',
      price: '$25000',
      minBuy: '20 unidades',
      description: 'Silla Gamming color rojo',
    },
    {
      name: 'Silla Gammer Superman',
      category: 'Sillas',
      slug: 'silla-gammer',
      image: '/images/silla2.jpg',
      price: '$23900',
      minBuy: '30 unidades',
      description: 'Silla Gamming Superman',
    },
    {
      name: 'Asic de minería T500',
      category: 'Asic',
      slug: 'asic',
      image: '/images/asic1.jpg',
      price: 'u$ 9500',
      minBuy: '1 unidades',
      description: 'Equipo de minería',
    },
    {
      name: 'Asic de mineria th20',
      category: 'Asic',
      slug: 'asic',
      image: '/images/asic2.jpg',
      price: 'u$ 10200',
      minBuy: '1 unidades',
      description: 'Equipo de minería',
    },
  ],
};
export default data;
